### ISSUE TITLE
long user name causes inconsistent format

### ISSUE THREAD

**Issue by amoswzw** [algolia/github-awesome-autocomplete#81]
![image](https://user-images.githubusercontent.com/16834522/40046544-cd197ed0-585f-11e8-96d2-e19e1d97a824.png)

**Comment by rayrutjes** [comment]
Thanks for reporting this @wangzewang .
Definitely something that should be adjusted.

**Comment by Haroenv** [comment]
```css
.aa-suggestion.aa-user {
  white-space: nowrap;
  overflow: hidden;
}
```

not ideal, but couldn't get ellipsis to work

**Comment by Haroenv** [comment]
some other experimentation with this in more of the classes could help as well:

```css
.aa-suggestion {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}
````
